# mission_map 안에서 로봇의 시작 위치와 방향을 결정하는 config
mission_tf_node:
  ros__parameters:
    # Frame names
    mission_frame: "mission_map"
    odom_frame: "odom"

    # mission_map 기준 Spot 시작 위치
    # 즉, odom frame의 원점이 mission_map 안에서 어디에 놓이는지 정의한다.
    start_x_m: 3.0
    start_y_m: 1.0
    start_z_m: 0.0

    # mission_map 기준 Spot 시작 방향
    # 단위: rad
    # 0.0    : mission_map x축 방향으로 시작
    # 1.5708 : mission_map y축 방향으로 시작
    start_yaw_rad: 0.0
