rl_locomotion_node:
  ros__parameters:
    policy_rate_hz: 50.0

    obs_dim: 47
    action_dim: 12
    action_clip: 100.0

    policy_backend: "onnx"
    require_model: true
    obs_clip: 100.0

    debug_publish_rate_hz: 2.0

    feedback_timeout_ms: 150.0
    imu_timeout_ms: 150.0
    status_timeout_ms: 150.0
    max_feedback_joint_velocity_rad_s: 300.0
    max_raw_action_abs: 10.0

    # 0 MODE_DISABLE
    # 1 MODE_STAND
    # 3 MODE_CROUCH
    # 4 MODE_E_STOP
    safe_mode: 1

    joint_names:
      - front_left_shoulder
      - front_left_leg
      - front_left_foot
      - front_right_shoulder
      - front_right_leg
      - front_right_foot
      - rear_left_shoulder
      - rear_left_leg
      - rear_left_foot
      - rear_right_shoulder
      - rear_right_leg
      - rear_right_foot

    default_joint_angles:
      - 0.0
      - -0.6
      - 1.1
      - 0.0
      - -0.6
      - 1.1
      - 0.0
      - -0.6
      - 1.1
      - 0.0
      - -0.6
      - 1.1

    joint_min_rad:
      - -0.548
      - -2.666
      - -0.100
      - -0.548
      - -2.666
      - -0.100
      - -0.548
      - -2.666
      - -0.100
      - -0.548
      - -2.666
      - -0.100

    joint_max_rad:
      - 0.548
      - 1.548
      - 2.590
      - 0.548
      - 1.548
      - 2.590
      - 0.548
      - 1.548
      - 2.590
      - 0.548
      - 1.548
      - 2.590

    max_joint_speed_rad_s: 0.75
    walk_start_cmd_norm: 0.01
    walk_start_ramp_s: 1.2
    walk_stop_ramp_s: 0.0
    reset_phase_on_walk_start: false
    reset_target_to_feedback_on_walk_start: true
